### ISSUE TITLE
项目还在继续吗？ 还维护不~  看着不错的一个项目

### ISSUE THREAD

**Issue by arleyGuoLei** [unclexiao/egg-mp#1]
so good ~

**Comment by unclexiao** [comment]
@arleyGuoLei 最近在做Flutter项目去了，可能较长一段时间（一个月）不会更新

**Comment by arleyGuoLei** [comment]
> @arleyGuoLei 最近在做Flutter项目去了，可能较长一段时间（一个月）不会更新

嗯哈~ flutter不错
